apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
spec:
  fileStore:
    external:
      bucket: byoc-staging-internal-staging-app-data
  ingress:
    enabled: false
    host: byoc-staging.dev.cloud.mattermost.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mattermost
spec:
  hostnames:
    - byoc-staging.dev.cloud.mattermost.com
