# Auto-generated by get-resource-names.sh on 2026-02-18 16:29:39
# Edit as needed. Source: source addons/docs/env.local.sh

# -----------------------------------------------------------------------------
# Core - Required for most operations
# -----------------------------------------------------------------------------
export RESOURCE_GROUP_NAME="chrisfickess-tfstate-azk"
export AZURE_SUBSCRIPTION_ID="95a937e7-e4a7-4f4b-9cb5-ce5affa2b458"

# -----------------------------------------------------------------------------
# Key Vault - Used by External Secrets for Mattermost DB, license
# -----------------------------------------------------------------------------
export KEYVAULT_NAME="mattermost-dev-chris-pgs"
export KV_SECRET_POSTGRES_CONNECTION_STRING="postgres-connection-string"
export KV_SECRET_POSTGRES_INTERNAL_PASSWORD="postgres-internal-password"
export KV_SECRET_POSTGRES_INTERNAL_USER="postgresinternaluser"
export KV_SECRET_MATTERMOST_LICENSE="mattermost-license-store"

# -----------------------------------------------------------------------------
# NFS Storage - Used by Mattermost PVC for file storage
# -----------------------------------------------------------------------------
export NFS_STORAGE_ACCOUNT="mattermostdevnfs"
export NFS_STORAGE_SHARE=""
export NFS_PRIVATE_ENDPOINT_NAME="mattermost-dev-nfs-pe"

# -----------------------------------------------------------------------------
# AKS Cluster - For kubectl access
# -----------------------------------------------------------------------------
export AKS_CLUSTER_NAME="mattermost-dev-chris-aks"

# -----------------------------------------------------------------------------
# PostgreSQL - For direct DB access (optional)
# -----------------------------------------------------------------------------
export POSTGRES_SERVER_NAME="mattermost-dev-chris-postgres-flex"

# -----------------------------------------------------------------------------
# VNet - For network/DNS verification
# -----------------------------------------------------------------------------
export VNET_NAME="chrisfickess-azk-vnet-dev"
export PRIVATE_DNS_ZONE_NAME="privatelink.file.core.windows.net"

# -----------------------------------------------------------------------------
# Tenant (for ClusterSecretStore - External Secrets)
# -----------------------------------------------------------------------------
export AZURE_TENANT_ID="7419f71d-0b07-4d0a-89b8-3a4be2ec8627"
