{{- if .Values.grafana.enabled }}
{{- include "flux-addons.helmrelease" (dict
    "name"        "grafana"
    "releaseName" "grafana"
    "namespace"   .Values.grafana.namespace
    "chart"       .Values.grafana.chart
    "global"      .Values.global) }}
{{- end }}
