---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mattermost
  namespace: {{ .Values.instance.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s-%s" .Values.global.aws.accountNumber .Values.global.aws.clusterName .Values.instance.irsaRoleSuffix }}
