# addons/clusters/azure/dev-chris/flux-system/gitrepository.yaml
# addons/clusters/azure/dev-chris/flux-system/gitrepository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mattermost-byoc-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: mattermost-byoc-infra
  url: ssh://git@ssh.github.com:443/mattermost/mattermost-byoc-infra.git
  ignore: |
    modules/*
    examples/*
    addons/clusters/*
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: planets-and-plans
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feature/flux-deploy-mattermost
  secretRef:
    name: planets-and-plans
  url: ssh://git@ssh.github.com:443/christopherfickess/planets-and-plans.git
  ignore: |
    modules/*
    stack/*
  include:
    - repository:
        name: mattermost-byoc-infra
      fromPath: addons/apps
      toPath: addons/base-apps
---

