{{- if and .Values.grafana.enabled .Values.externalSecrets.enabled ((.Values.grafana.adminExternalSecret).secretKey) }}
{{- $app := .Values.grafana }}
{{- $es  := $app.adminExternalSecret }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $app.adminPasswordSecretRef.name | default "grafana-admin-secret" }}
  namespace: {{ $app.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: {{ $app.adminPasswordSecretRef.name | default "grafana-admin-secret" }}
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key:      {{ $es.secretKey }}
        property: {{ $es.userProperty | default "admin-user" }}
    - secretKey: admin-password
      remoteRef:
        key:      {{ $es.secretKey }}
        property: {{ $es.passwordProperty | default "admin-password" }}
{{- end }}
