#cloud-config
packages:
  - amazon-ssm-agent
  - nginx
  - certbot
  - python3-certbot-nginx
  - jq
  - postgresql15
  - wget
  - curl
  - gnupg2

write_files:
  - path: /etc/systemd/system/mattermost.service
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Mattermost
      After=network.target
      Requires=network.target

      [Service]
      Type=simple
      User=mattermost
      Group=mattermost
      WorkingDirectory=/opt/mattermost
      ExecStart=/opt/mattermost/bin/mattermost
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target

  - path: /etc/nginx/sites-available/mattermost
    owner: root:root
    permissions: "0644"
    # HTTP configuration
    content: |
      server {
          listen 80;
          server_name _;

          client_max_body_size 100M;

          location / {
              proxy_pass http://127.0.0.1:8065;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    # HTTPS configuration with Certbot will handle this
    # content: |
    #   server {
    #       listen 80;
    #       server_name ${mattermost_domain};

    #       # Redirect all HTTP requests to HTTPS
    #       return 301 https://$host$request_uri;
    #   }

    #   server {
    #       listen 443 ssl;
    #       server_name _;

    #       ssl_certificate /etc/letsencrypt/live/${mattermost_domain}/fullchain.pem;
    #       ssl_certificate_key /etc/letsencrypt/live/${mattermost_domain}/privkey.pem;

    #       # Increase upload size limit
    #       client_max_body_size 100M;

    #       location / {
    #           proxy_pass http://localhost:8065;
    #           proxy_set_header X-Real-IP $remote_addr;
    #           proxy_set_header Host $host;
    #           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #           proxy_set_header X-Forwarded-Proto $scheme;
    #           proxy_buffering off;
    #           proxy_http_version 1.1;
    #           proxy_set_header Upgrade $http_upgrade;
    #           proxy_set_header Connection "upgrade";
    #       }
    #   }

runcmd:
  # Logging
  - LOG_DIR=/var/log/
  - LOG_FILE="$LOG_DIR/cloud-init-$(date +%Y%m%d-%H%M%S).log"
  - exec > >(tee -a $LOG_FILE) 2>&1

  # Enable and start SSM Agent
  - systemctl enable amazon-ssm-agent
  - systemctl start amazon-ssm-agent
  - systemctl restart sshd

  # Update System
  - dnf update -y
  - amazon-linux-extras enable corretto8

  # Install required packages
  - |
    dnf install -y --allowerasing wget \
      curl \
      gnupg2 \
      postgresql15 \
      jq \
      nginx
  # \
  #    certbot \
  #    python3-certbot-nginx

  - dnf clean all

  # Download and install Mattermost
  # - wget https://releases.mattermost.com/${mattermost_version}/mattermost-${mattermost_version}-linux-amd64.tar.gz
  # - tar -xvzf mattermost-${mattermost_version}-linux-amd64.tar.gz
  - |
    wget -P /tmp/ https://releases.mattermost.com/${mattermost_version}/mattermost-enterprise-${mattermost_version}-linux-amd64.tar.gz \
    && echo "Mattermost tarball downloaded successfully." \
    || echo "Failed to download Mattermost tarball."

  - |
    tar -xvzf /tmp/mattermost-enterprise-${mattermost_version}-linux-amd64.tar.gz -C /tmp/ \
    && echo "Untar Mattermost successfully." \
    || echo "Failed to untar Mattermost."
  - mv -f /tmp/mattermost/ /opt/mattermost
  - mkdir /opt/mattermost/data
  - useradd --system --user-group mattermost
  - chown -R mattermost:mattermost /opt/mattermost
  - chmod -R g+w /opt/mattermost
  - mkdir -p /home/mattermost
  - chown -R mattermost:mattermost /home/mattermost

  # Fetch DB credentials from SSM
  - |
    MATTERMOST_DB_USERNAME=$(aws ssm get-parameter --name \
        "${username_param}" --with-decryption \
        --query "Parameter.Value" --output text)
  - |
    MATTERMOST_DB_PASSWORD=$(aws ssm get-parameter --name \
        "${password_param}" --with-decryption \
        --query "Parameter.Value" --output text)

  - MATTERMOST_DB_ENDPOINT="${rds_endpoint}"

  # Update Mattermost config.json DataSource
  - MATTERMOST_CONFIG_FILE="/opt/mattermost/config/config.json"
  - MATTERMOST_DATASOURCE="postgres://$MATTERMOST_DB_USERNAME:$MATTERMOST_DB_PASSWORD@$MATTERMOST_DB_ENDPOINT:5432/${mattermost_db_name}?sslmode=require&connect_timeout=10"
  - |
    jq --arg dsn "$MATTERMOST_DATASOURCE" \
        '.SqlSettings.DataSource = $dsn' \
        "$MATTERMOST_CONFIG_FILE" > "$MATTERMOST_CONFIG_FILE.tmp"

  - mv -f "$MATTERMOST_CONFIG_FILE.tmp" "$MATTERMOST_CONFIG_FILE"
  - chown mattermost:mattermost "$MATTERMOST_CONFIG_FILE"

  # Start Mattermost service
  - systemctl daemon-reload
  - systemctl enable mattermost
  - systemctl start mattermost
  - systemctl status mattermost
  # ----------------------------------------------------------------------------
  # Fetch Mattermost config from S3 and set proper ownership
  # To Work on Soon
  # - aws s3 cp s3://my-mattermost-config-bucket/config.json /home/mattermost/mattermost/config/config.json
  # - chown mattermost:mattermost /home/mattermost/mattermost/config/config.json
  # ----------------------------------------------------------------------------
  # Setup NQINX Configuration and Deploy Load Balancer

  # Setup Nginx
  - ln -s /etc/nginx/sites-available/mattermost /etc/nginx/conf.d/mattermost.conf
  # - rm -f /etc/nginx/sites-enabled/default
  - nginx -t
  - systemctl enable nginx
  - systemctl restart nginx

  # Obtain SSL certificates via Certbot
  # - |
  #   certbot --nginx -d ${mattermost_domain} \
  #     --non-interactive \
  #     --agree-tos \
  #     --email ${mattermost_email} \
  #     --redirect
  # - systemctl status certbot.timer
