#cloud-config

users:
  - name: ${ADMIN_USERNAME}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ${PUBLIC_KEY_CONTENT}

package_update: true
package_upgrade: true

packages:
  - dnf
  - curl
  - jq
  - git
  - vim
  - sudo
  - unzip

runcmd:
  - echo "Starting cloud-init runcmd..." | tee -a /var/log/cloud-init-user-data.log

  # Import Microsoft GPG keys
  - rpm --import https://packages.microsoft.com/keys/microsoft-2025.asc
  - rpm --import https://packages.microsoft.com/keys/microsoft.asc

  # Add Azure CLI repo
  - |
    cat <<EOF > /etc/yum.repos.d/azure-cli.repo
    [azure-cli]
    name=Azure CLI
    baseurl=https://packages.microsoft.com/yumrepos/azure-cli
    enabled=1
    gpgcheck=1
    gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    EOF

  # Install Azure CLI
  - sudo dnf install -y libffi \
    libffi-devel \
    python3-cffi \
    python3-cryptography
  - sudo dnf install -y azure-cli

  # Install kubelogin
  - sudo curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.34/kubelogin-linux-amd64.zip
  - sudo unzip kubelogin-linux-amd64.zip -d /tmp
  - sudo mv /tmp/bin/linux_amd64/kubelogin /usr/local/bin/
  - sudo rm -f kubelogin-linux-amd64.zip

  # Install kubectl
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/

  # Set permissions for user files
  - sudo mkdir -p /home/${ADMIN_USERNAME}
  - sudo chown -R ${ADMIN_USERNAME}:${ADMIN_USERNAME} /home/${ADMIN_USERNAME}
  - echo "export PATH=$PATH:/usr/local/bin" >> /home/${ADMIN_USERNAME}/.bashrc
  - chown ${ADMIN_USERNAME}:${ADMIN_USERNAME} /home/${ADMIN_USERNAME}/.bashrc

write_files:
  - path: /home/${ADMIN_USERNAME}/setup-aks-access.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      export GREEN='\033[0;32m'
      export MAGENTA='\033[0;35m'
      export NC='\033[0m'

      AKS_NAME="${AKS_NAME}"
      RESOURCE_GROUP_NAME="${RESOURCE_GROUP_NAME}"
      MANAGED_IDENTITY_ID="${MANAGED_IDENTITY_ID}"

      echo -e "$${MAGENTA}Logging in using Managed Identity...$${NC}"
      az login --identity --username "$MANAGED_IDENTITY_ID"

      echo -e "$${MAGENTA}Retrieving AKS credentials...$${NC}"
      az aks get-credentials \
        --resource-group "$RESOURCE_GROUP_NAME" \
        --name "$AKS_NAME" \
        --overwrite-existing

      kubelogin convert-kubeconfig -l azurecli

      echo -e "$${MAGENTA}Verifying kubectl access...$${NC}"
      kubectl cluster-info
      kubectl get nodes

      echo -e "$${GREEN}AKS access configured successfully!$${NC}"

  - path: /home/${ADMIN_USERNAME}/README.md
    permissions: "0644"
    owner: ${ADMIN_USERNAME}:${ADMIN_USERNAME}
    content: |
      # Jumpbox Setup Complete

      ## Installed Tools
      - Azure CLI
      - kubelogin
      - kubectl
      - git
      - jq
      - vim

      ## Connecting to AKS
      After connecting via Azure Bastion, run:
      ```bash
      ./setup-aks-access.sh
      ```

      ## Manual Commands
      ```bash
      az login --identity --username <managed-identity-client-id>
      az aks get-credentials --resource-group <resource-group> --name <aks-name>
      kubelogin convert-kubeconfig -l azurecli
      kubectl get nodes
      ```

      ## Cluster Info
      - AKS Name: ${AKS_NAME}
      - Resource Group: ${RESOURCE_GROUP_NAME}
      - Managed Identity Client ID: ${MANAGED_IDENTITY_ID}

final_message: "Jumpbox setup completed successfully at $(date)"
