# addons/clusters/byoc-staging-iron-badger/apps/velero/helmrelease-patch.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m
  values:
    namespace:
      labels:
        environment: dev-chris
    podAnnotations:
      app.kubernetes.io/environment: dev-chris
    configuration:
      podLabels:
        app.kubernetes.io/environment: dev-chris

      backupStorageLocation:
        - provider: aws
          name: default
          bucket: cloud-velero-dev-chris
          config:
            region: us-east-2
          default: true

      volumeSnapshotLocation:
        - provider: aws
          name: default
          config:
            region: us-east-2

    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 16G
    schedules:
      backup:
        disabled: false
        schedule: "0 8 * * *"
        labels:
          environment: dev-chris
        annotations:
          environment: dev-chris
        template:
          ttl: "720h0m0s"
        useOwnerReferencesInBackup: true
    tolerations:
      - key: "utilities"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
