# addons/clusters/byoc-staging-iron-badger/apps/velero/helmrelease-patch.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m

  valuesFrom:
    - kind: File
      path: ../../values.yaml
