# addons/clusters/byoc-staging-internal/apps/external-secrets/clustersecretstore.yaml

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-secretsmanager
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: https://mattermost-dev-chris-postgres-flex.vault.azure.net/
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
      tenantId: 95a937e7-e4a7-4f4b-9cb5-ce5affa2b458
      vaultObjectCache:
        enabled: true
        ttl: 5m
        maxEntries: 1000
