# addons/clusters/byoc-staging-internal/apps/external-secrets/clustersecretstore.yaml

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  namespace: external-secrets
spec:
  provider:
    azure:
      service: KeyVault
      vaultUrl: https://byoc-kv.vault.azure.net/
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
