# addons/clusters/byoc-staging-internal/apps/external-secrets/clustersecretstore.yaml

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-secretsmanager
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: https://mattermost-dev-chris-kv.vault.azure.net/
      authType: WorkloadIdentity
      # tenantId from service account annotation - do not duplicate here
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
