# addons/clusters/byoc-staging-internal/apps/external-secrets/clustersecretstore.yaml

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-secretsmanager
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: https://mattermost-dev-chris-pgs.vault.azure.net/
      authType: WorkloadIdentity
      tenantId: "7419f71d-0b07-4d0a-89b8-3a4be2ec8627"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
