# addons/clusters/byoc-staging-internal/apps/external-secrets/helmrelease-patches.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  # Use this to override the IRSA per cluster/account
  values:
    serviceAccount:
      automount: true
      create: true
      name: "external-secrets"
      annotations:
        azure.workload.identity/client-id: "/subscriptions/95a937e7-e4a7-4f4b-9cb5-ce5affa2b458/resourceGroups/chrisfickess-tfstate-azk/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mattermost-dev-chris-external-secrets-identity"
  interval: 5m0s
