# addons/clusters/byoc-staging-internal/apps/external-secrets/helmrelease-patches.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  values:
    serviceAccount:
      create: true
      name: external-secrets
      automount: true
      annotations:
        azure.workload.identity/client-id: "8d7667d6-5229-413f-b2f8-1a4ff53fe4eb"
  interval: 5m0s
