# addons/clusters/byoc-staging-internal/apps/external-secrets/helmrelease-patches.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  values:
    # Use our own SA - base chart overwrites annotations on "external-secrets"
    serviceAccount:
      create: false
      name: external-secrets-azure
      automount: true
    # Required for Azure Workload Identity token injection
    podLabels:
      azure.workload.identity/use: "true"
  interval: 5m0s
