# addons/clusters/byoc-staging-internal/apps/external-secrets/helmrelease-patches.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  values:
    serviceAccount:
      create: true
      name: external-secrets
      automount: true
      annotations:
        # comes from output at aks module
        # module.mattermost_aks.identity_client_ids["external-secrets"]
        azure.workload.identity/client-id: "b906bc86-26bc-4a34-b573-58b9ba6654b0"
        azure.workload.identity/tenant-id: "7419f71d-0b07-4d0a-89b8-3a4be2ec8627"
        azure.workload.identity/use: "true"
        eks.amazonaws.com/role-arn: null
  interval: 5m0s
