# addons/clusters/byoc-staging-internal/apps/external-secrets/helmrelease-patches.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  # Use this to override the IRSA per cluster/account
  values:
    serviceAccount:
      automount: true
      create: true
      name: "external-secrets"
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::926412419614:role/mattermost-external-secrets"
  interval: 5m0s
