apiVersion: v1
kind: Pod
metadata:
  name: test-es
  namespace: external-secrets
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: external-secrets
  containers:
    - name: cli
      image: mcr.microsoft.com/azure-cli
      command: ["sleep", "3600"]
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
  restartPolicy: Never
