# addons/apps/velero/release.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m

  chart:
    spec:
      chart: velero
      version: "11.3.2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 1h # Checks the upstream chart for updates every hour

  install:
    createNamespace: true

  upgrade:
    cleanupOnFail: true
    timeout: 5m # upgrade operation times out after 5 minutes

  valuesFrom:
    - kind: ConfigMap
      name: velero-values
      valuesKey: values.yaml
