# addons/clusters/azure/dev-chris/apps/keycloak/postgres/release.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-postgres
  namespace: flux-system
spec:
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
  interval: 10m
  targetNamespace: keycloak

  chart:
    spec:
      chart: postgresql
      version: "16.x" # Use a version constraint to control upgrades
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h # How often to check for new chart versions
  install:
    # Create the target namespace if it does not exist
    createNamespace: true
    remediation:
      retries: 3 # Retry up to 3 times if install fails
  upgrade:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: keycloak-postgres-values
      valuesKey: values.yaml
