apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database
  namespace: mattermost
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secretsmanager
  target:
    name: database
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-internal-password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgresinternaluser
    - secretKey: DB_CONNECTION_STRING
      remoteRef:
        key: postgres-connection-string
