apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database
  namespace: mattermost
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secretsmanager
  target:
    name: database
    creationPolicy: Owner
  data:
    # - secretKey: DB_CONNECTION_STRING
    #   remoteRef:
    #     key: postgres-connection-string
    # - secretKey: MM_CONFIG
    #   remoteRef:
    #     key: postgres-connection-string
    # - secretKey: MM_SQLSETTINGS_DATASOURCEREPLICAS
    #   remoteRef:
    #     key: postgres-connection-string
    # - secretKey: DB_CONNECTION_CHECK_URL
    #   remoteRef:
    #     key: postgres-connection-string
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-internal-password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgresinternaluser

        
