# addons/clusters/byoc-staging-internal/apps/mattermost/patches.yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
spec:
  replicas: 2
  fileStore:
    external:
      externalVolume:
        volumeClaimName: mattermost-nfs-pvc
  # fileStore:
  #   external:
  #     bucket: mattermostdevchrisshare
  #     url: https://mattermostdevchris.file.core.windows.net
  #     secret: filestore
  ingress:
    enabled: true
    # httproute_enabled: false
    host: dev-chris.dev.cloud.mattermost.com
  mattermostEnv:
  - name: MM_FILESETTINGS_AMAZONS3SSE
    value: "false"
  - name: MM_FILESETTINGS_AMAZONS3SSL
    value: "false"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mattermost
$patch: delete

# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: mattermost-
# $patch: delete