# addons/clusters/byoc-staging-internal/apps/mattermost/patches.yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
spec:
  replicas: 1 # Use 1 until HA license is available
  fileStore:
    externalVolume:
      volumeClaimName: mattermost-nfs-pvc
  # fileStore:
  #   external:
  #     bucket: mattermostdevchrisshare
  #     url: https://mattermostdevchris.file.core.windows.net
  #     secret: filestore
  ingress:
    enabled: false
    # Using mattermost-lb LoadBalancer service with Azure PIP instead of nginx ingress
    # CNAME: dev-chris.dev.cloud.mattermost.com -> mattermost-dev-mattermost.eastus2.cloudapp.azure.com
    host: dev-chris.dev.cloud.mattermost.com
  image: mattermost/mattermost-enterprise-fips-edition
  mattermostEnv:
    # OpenID Settings
    # use SAML
    # - name: MM_OPENIDSETTINGS_ENABLE
    #   value: "true"
    # - name: MM_OPENIDSETTINGS_BUTTONTEXT
    #   value: "Login with Keycloak"
    # - name: MM_OPENIDSETTINGS_DISCOVERYENDPOINT
    #   value: "https://<keycloak-external-url>/realms/mattermost/.well-known/openid-configuration"
    # - name: MM_OPENIDSETTINGS_ID
    #   value: "<your-client-id>"
    # - name: MM_OPENIDSETTINGS_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: keycloak-oidc
    #       key: client-secret
    - name: MM_SITEURL
      value: "https://dev-chris.dev.cloud.mattermost.com"
    - name: MM_FILESETTINGS_DRIVERNAME
      value: "local"
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "false"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "false"
    - name: MM_LICENSE
      value: ""
    # Reduce log noise in dev
    - name: MM_CLUSTERSETTINGS_ENABLE
      value: "false"
    - name: MM_EMAILSETTINGS_SMTPSERVER
      value: ""
    - name: MM_PLUGINSETTINGS_PLUGINSTATES
      value: '{"com.mattermost.calls":{"Enable":false},"mattermost-ai":{"Enable":false}}'
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mattermost
$patch: delete
# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: mattermost-
# $patch: delete
