# addons/clusters/byoc-staging-internal/apps/mattermost/patches.yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
spec:
  fileStore:
    nfs:
      server: mattermostdevchrisnfs.privatelink.file.core.windows.net
      path: /mattermostdevchrisshare
  ingress:
    enabled: false
    host: byoc-staging.dev.cloud.mattermost.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mattermost
spec:
  hostnames:
    - byoc-staging.dev.cloud.mattermost.com
