# addons/clusters/byoc-staging-internal/apps/mattermost/patches.yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
spec:
  replicas: 1 # Use 1 until HA license is available
  fileStore:
    externalVolume:
      volumeClaimName: mattermost-nfs-pvc
  # fileStore:
  #   external:
  #     bucket: mattermostdevchrisshare
  #     url: https://mattermostdevchris.file.core.windows.net
  #     secret: filestore
  ingress:
    enabled: true
    # httproute_enabled: false
    # host: dev-chris.dev.cloud.mattermost.com ## this is the old domain with IP address
    # Use ALB FQDN from Terraform (mattermost-dev-chris-alb.eastus2.cloudapp.azure.com)
    # Or CNAME your domain to LB_FQDN and use that here
    host: mattermost-dev-chris-alb.eastus2.cloudapp.azure.com
  mattermostEnv:
    - name: MM_SITEURL
      value: "https://mattermost-dev-chris-alb.eastus2.cloudapp.azure.com"
    - name: MM_FILESETTINGS_DRIVERNAME
      value: "local"
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "false"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "false"
    - name: MM_LICENSE
      value: ""
    # Reduce log noise in dev
    - name: MM_CLUSTERSETTINGS_ENABLE
      value: "false"
    - name: MM_EMAILSETTINGS_SMTPSERVER
      value: ""
    - name: MM_PLUGINSETTINGS_PLUGINSTATES
      value: '{"com.mattermost.calls":{"Enable":false},"mattermost-ai":{"Enable":false}}'
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mattermost
$patch: delete
# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: mattermost-
# $patch: delete
