apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermost-nfs-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # Azure Files NFS requires path: /<storage-account-name>/<file-share-name>
  # Verify share name from: terraform output -json nfs | jq -r '.nfs_share_name'
  nfs:
    server: mattermostdevchrisnfs.privatelink.file.core.windows.net
    path: /mattermostdevchrisnfs/mattermostdevchrisshare
  mountOptions:
    - vers=4
    - minorversion=1
    - sec=sys
    - nconnect=4
    - noresvport
    - actimeo=30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-nfs-pvc
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: mattermost-nfs-volume

