apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermost-nfs-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: mattermostdevchrisnfs.privatelink.file.core.windows.net
    path: /mattermostdevchrisshare
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-nfs-pvc
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: mattermost-nfs

