# addons/clusters/azure/dev-chris/apps/mattermost/service.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mattermost
  namespace: mattermost
  annotations:
    # kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: azure-application-gateway
  tls:
    - hosts:
        - dev-chris.dev.cloud.mattermost.com
      secretName: mattermost-tls
  rules:
    - host: dev-chris.dev.cloud.mattermost.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mattermost
                port:
                  number: 8065
